Remove trailing argument for generate_lua_types_file()
This function is declared in lua_base.h with zero arguments.

src/console_cmd.c:2137:5: error: too many arguments to function ‘generate_lua_types_file’; expected 0, have 1
 2137 |     generate_lua_types_file(args);
      |