Fix conditional to handle miniupnpc API changes
The real reason why this needs the last two arguments is not because of the platform but because of a API change in miniupnpc 2.2.8. Windows most probably already has a newer one, and when building on a Linux machine with an equally new miniupnpc, it fails as well. (See https://github.com/hrydgard/ppsspp/issues/19333)

src/net_portforward.cpp:216:58: error: too few arguments to function ‘int UPNP_GetValidIGD(UPNPDev*, UPNPUrls*, IGDdatas*, char*, int, char*, int)’
  216 |     int internet_gateway_device_result = UPNP_GetValidIGD(device_list, &upnp_urls, &upnp_data, upnp_lanaddr, sizeof(upnp_lanaddr));
      |                                          ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~