Initialize huf_table structs to zero to prevent warning
huf_table structs may be unitialized due to huf_table_read() returning early in
case of an error. Newer GCC versions complain about this.

src/bflib_dernc.c:299:16: error: ‘raw.num’ may be used uninitialized [-Werror=maybe-uninitialized]
  299 |     for (i=0; i<h->num; i++)
      |               ~^~~~~~~